# enable bluetooth
CONFIG_BT=y

# increase bluetooth signal power
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable deep sleep support
# CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
# 3_600_000 ms = 60 minutes
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# "Eager Debouncing"
# Trying to lower the input lag.
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
